### PR TITLE
Adding ComparisonHC to cblearn

### PR DESCRIPTION
**Pull request by Conzel**
This pull request adds a modified version of the ComparisonHC algorithm (https://github.com/mperrot/ComparisonHC, https://arxiv.org/abs/1811.00928) to cblearn. This also introduces a new module "cluster" for ordinal clusterings (as opposed to only embeddings). 

This PR contains:
- New Class ComparisonHC with sklearn-like interface
- New Module "cluster", accessible via cblearn.cluster, which contains classes for ordinal clustering
- Tests with >90% coverage for ComparisonHC
- Documentation for all public methods

What is still missing before it can be merge
- [x] Check & proofread generated documentation thoroughly
- [x] Clear License problems with original authors (they use GPL-3 vs our MIT)

### CODE REVIEW

**Comment by Conzel** [comment]
@dekuenstle The error this time looks like I didn't cause it – any ideas / have seen that before?

**Comment by Conzel** [comment]
Licensing problem solved, as ComparisonHC changed its license to MIT, thanks to @mperrot.

**Comment by dekuenstle** [comment]
Thanks a lot for your work! Please apologise the delay in merging: I need some time for proper testing and did not get to it yet.

**Review by dekuenstle — APPROVED** [review]

**Comment by Conzel** [comment]
@dekuenstle looks great, thank you for your efforts!

**Pull request merged**
